spring:
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  mongodb:
    embedded:
      version: "5.0.0"
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: off
    read-concern: local