DROP TABLE IF EXISTS COMMENTS;

DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS AUTHORS;

DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS
(
    ID      SERIAL PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE GENRES
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        SERIAL PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    GENRE_ID  BIGINT REFERENCES GENRES (id)
);

CREATE TABLE COMMENTS
(
    ID           SERIAL PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID      BIGINT NOT NULL REFERENCES BOOKS (id) ON DELETE CASCADE
);