DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS acl_sid;
DROP TABLE IF EXISTS acl_class;
DROP TABLE IF EXISTS acl_entry;
DROP TABLE IF EXISTS acl_object_identity;

CREATE TABLE AUTHORS
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    GENRE_ID  BIGINT REFERENCES GENRES (id)
);

CREATE TABLE COMMENTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID      BIGINT NOT NULL REFERENCES BOOKS (id) ON DELETE CASCADE
);

CREATE TABLE ACL_SID
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRINCIPAL BIGINT       NOT NULL,
    SID       VARCHAR(100) NOT NULL
);

CREATE TABLE ACL_CLASS
(
    ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASS VARCHAR(255) NOT NULL
);

CREATE TABLE ACL_OBJECT_IDENTITY
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    OBJECT_ID_CLASS    BIGINT NOT NULL REFERENCES ACL_CLASS (id),
    OBJECT_ID_IDENTITY BIGINT NOT NULL,
    PARENT_OBJECT      BIGINT DEFAULT NULL REFERENCES ACL_OBJECT_IDENTITY (id),
    OWNER_SID          BIGINT DEFAULT NULL REFERENCES ACL_SID (id),
    ENTRIES_INHERITING BIGINT NOT NULL
);

CREATE TABLE ACL_ENTRY
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACL_OBJECT_IDENTITY BIGINT NOT NULL REFERENCES ACL_OBJECT_IDENTITY (id),
    ACE_ORDER           BIGINT NOT NULL,
    SID                 BIGINT NOT NULL REFERENCES ACL_SID (id),
    MASK                BIGINT NOT NULL,
    GRANTING            BIGINT NOT NULL,
    AUDIT_SUCCESS       BIGINT NOT NULL,
    AUDIT_FAILURE       BIGINT NOT NULL
);