spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: ./logs/log-file.log