DROP TABLE IF EXISTS COMMENTS;

DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS AUTHORS;

DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);


CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    GENRE_ID  BIGINT REFERENCES GENRES (id)
);

CREATE TABLE COMMENTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID      BIGINT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE
);