DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS AUTHORS;

DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS
(
    ID      BIGSERIAL PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE GENRES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        BIGSERIAL PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    GENRE_ID  BIGINT REFERENCES GENRES (id)
);


