DROP TABLE IF EXISTS AUTHORS;

DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS
(
    ID      BIGINT PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);
CREATE TABLE test
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (id),
    GENRE_ID  BIGINT REFERENCES GENRES (id)
);


