spring:
  application:
    name: aaa
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
logging:
  file:
    name: ./logs/log-file.log
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    keyComments:
      circuitBreaker:
        errorThresholdPercentage: 30
        sleepWindowInMilliseconds: 3000
      metrics:
        rollingStats:
          timeInMilliseconds: 5000
    keyAuthor:
      circuitBreaker:
        errorThresholdPercentage: 40
        sleepWindowInMilliseconds: 2500
      metrics:
        rollingStats:
          timeInMilliseconds: 5000
    keyBook:
      circuitBreaker:
        errorThresholdPercentage: 30
        sleepWindowInMilliseconds: 4000
      metrics:
        rollingStats:
          timeInMilliseconds: 4500
    keyGenre:
      circuitBreaker:
        errorThresholdPercentage: 30
        sleepWindowInMilliseconds: 1000
      metrics:
        rollingStats:
          timeInMilliseconds: 4000